### PR TITLE
Update to version 0.1b4

### PR DESCRIPTION
**Pull request by frreiss**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [NA] Bumped the build number (if the version is unchanged)
* [NA] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This PR updates the `text-extensions-for-pandas` package to version 0.1b4. This version is a minor update to 0.1b3.

### CODE REVIEW

**Comment by frreiss** [comment]
@BryanCutler can you have a look at this and make sure I did the update correctly?

**Review by BryanCutler — COMMENTED** [review]
Looks good, the only thing is it looks like this is not building for python 3.6. If you want to change that it would be this line under `build`
`skip: true  # [win or py<37]` to `py<36`

**Comment by frreiss** [comment]
Thanks for catching that problem, @BryanCutler! Since this release is primarily about adding Python 3.6 support, enabling the 3.6 build is kind of important. Updated the value of `skip`.

**Review by BryanCutler — APPROVED** [review]
LGTM

**Pull request merged**
